### ISSUE TITLE
Partial ownership of NFT

### ISSUE THREAD

**Issue by iamjaspreetsingh** [MythicalGames/dgoods#13]
There may be digital assets like  videos, e-books, music, games, photography etc. where partial ownership can be of great value. When owing the partial ownership on any NFT (say of any particular video) and allowing the person to sell their % rights may allow the public participation in such valuable assets too. 
eg. for any ebook, ```ebooks``` category and ```harrypotter``` token name can be created,  there may be many stakeholders like publisher, author, retailer, distributor etc. The token ownership may be issued as per their percentage holdings of their rights. For that we can create a token say ```PER``` which can be issued maximum 100 (denoting 100%) for any token. Similarly for videos, photography, music etc. too. 
What's your opinion?

**Comment by zlnvch** [comment]
You can use fungible tokens for this.

Create a fungible token with category ebooks and token name harrypotter, with a max supply of something like 100.00.

Then, however many tokens someone has, represents their percentage.

**Comment by iamjaspreetsingh** [comment]
@znebby you are right, we can do that but we can't list and buy that currently, i suppose. Also, to avoid it behave it as a fungible token, for a unique asset one shall make it non fungible and issue PER tokens against it (that are fungible but stable and limited to 100 for a particular token). I have tried to implement it at https://github.com/Quillhash/dnfts. Please review it !

**Comment by iamjaspreetsingh** [comment]
I believe the use case of this may be entirely different, so it may be better as a different standard altogether. Kindly review it at https://github.com/Quillhash/dNFTs.
