### ISSUE TITLE
The quantity value when issuing an NFT is ignored

### ISSUE THREAD

**Issue by dbendt** [MythicalGames/dgoods#16]
In the ```issue``` action, supplying any quantity to the action will always produce 1 NFT. To maintain consistency with fungible tokens, I'd suggest either separating ```issue``` as it's own action ```issuenft```, or loop through the quantity value provided and mint the supplied number of NFTs.

**Comment by cthacker** [comment]
This has been addressed and updated in the develop branch -- along with many other changes. Check it out! It will be merged into master and released shortly.
