### ISSUE TITLE
Question: What is the best way to query the dgoodstats table?

### ISSUE THREAD

**Issue by dbendt** [MythicalGames/dgoods#8]
As a contract owner, if I forget the "token name" used after I've created a dgood how am I able to look it up again?

**Comment by cthacker** [comment]
You can get all of the entries with a given category, and if you forget the categories you can look them up in the categoryinfo table.

**Comment by dbendt** [comment]
Okay, I see what my issue was. If you use a category name less than 12 characters, it doesn't appear when querying via cleos or eos-js. May want to add a check to verify valid category names.

**Comment by cthacker** [comment]
You can use a category name up to 12 characters a-z, 1-5 but it works with less than that as well.
